"""Initial migration

Revision ID: a09bf4311190
Revises: 
Create Date: 2023-07-30 18:50:47.618069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09bf4311190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=86), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=86), nullable=False),
    sa.Column('username', sa.String(length=86), nullable=True),
    sa.Column('pwd', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('id_owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    op.drop_table('user')
    # ### end Alembic commands ###
